# General

title: Ateneo Molina de Segura
description: El Ateneo Villa de Molina de Segura es una asociación que comenzó su andadura en Noviembre de 2014 con la voluntad expresa de ser un lugar donde pudieran manifestarse y defenderse todas las ideas.

# Footer

twitter: https://twitter.com/ateneomolina
facebook: https://www.facebook.com/ateneomolina
email: ateneomolinadesegura@gmail.com

# Build

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing. The following items will not be processed, by default.

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - art
   - scripts
   - LICENSE
   - README.md